site_name: mywiki
site_url: https://yuriyteplyakov.github.io/mywiki/
nav:
  - index: index.md
  - GIT: GIT/git.md
  - CHPU:
    - Turn-mill:
      - TMC 6510: CHPU/TMC6510.md

theme:
  name: material
  features:
        - navigation.tabs
        - navigation.sections
        - toc.integrate
        - navigation.top
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.annotation
        - content.code.copy
  language: ru
  palette:
        - scheme: default
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
          primery: teal
          accent: purple
        - scheme: slate
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode
          primery: teal
          accent: lime

dev_addr:
  127.0.0.1:8200

markdown_extensions:
    - admonition
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

collapse_single_pages: true